---
sudo: required
dist: trusty

language: generic

env:
  # - ANSIBLE_VERSION="1.9" PHP_VERSION="5.6.21" # Paths in 1.9 are currently broken
  - ANSIBLE_VERSION="2.0" PHP_VERSION="5.6.21"
  # - ANSIBLE_VERSION="1.9" PHP_VERSION="7.0.6"
  - ANSIBLE_VERSION="2.0" PHP_VERSION="7.0.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - sudo -H pip install "ansible~=$ANSIBLE_VERSION"

  - sudo ansible-galaxy install bbatsche.Base
  - sudo ansible-galaxy install bbatsche.Nginx

  - echo localhost ansible_connection=local ansible_ssh_user=$USER > inventory

  - travis_wait ansible-playbook -i inventory provision-playbook.yml
script:
  # Syntax check
  - ansible-playbook -i inventory travis-playbook.yml --syntax-check

  # Play test
  - "cat #!/bin/sh >> play.sh"
  - cat sudo -E su $USER -c 'ansible-playbook -i inventory travis-playbook.yml -ephp_version=$PHP_VERSION' >> play.sh
  - travis_wait 40 play.sh

  # Idempotence test
  - >
    sudo -E su $USER -c 'ansible-playbook -i inventory travis-playbook.yml -ephp_version=$PHP_VERSION
    | grep -q "changed=0.*failed=0"
    && (echo "Idempotence test: pass" && exit 0)
    || (echo "Idempotence test: fail" && exit 1)'

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
