---
sudo: required
dist: trusty

language: generic

env:
  global:
    - ANSIBLE_LOCAL_TEMP=/tmp/ansible
    - ANSIBLE_REMOTE_TEMP=/tmp/ansible
  matrix:
    - ANSIBLE_VERSION="1.9"
    - ANSIBLE_VERSION="2.0"
    - ANSIBLE_VERSION="2.1"
    - ANSIBLE_VERSION="1.9" PHP_VERSION="5.6.21"
    - ANSIBLE_VERSION="2.0" PHP_VERSION="5.6.21"
    - ANSIBLE_VERSION="2.1" PHP_VERSION="5.6.21"
    - ANSIBLE_VERSION="1.9" PHP_VERSION="7.0.6"
    - ANSIBLE_VERSION="2.0" PHP_VERSION="7.0.6"
    - ANSIBLE_VERSION="2.1" PHP_VERSION="7.0.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - rvm use default
  - sudo gem install bundler
install:
  - sudo -H pip install ansible==${ANSIBLE_VERSION}.*

  - bundle install

  - sudo ansible-galaxy install bbatsche.Base
  - sudo ansible-galaxy install bbatsche.Nginx

  - echo localhost ansible_connection=local ansible_ssh_user=$USER > inventory

  - ansible-playbook -i inventory provision-playbook.yml --skip-tags timezone,sysctl,apt,ruby,node,bash,swap

  # Delete Travis provided phpenv
  - rm -rf $HOME/.phpenv
before_script:
  - "echo #!/bin/sh >> play.sh"
  - echo "sudo -E su $USER -c 'ansible-playbook -i inventory travis-playbook.yml'" >> play.sh
  - chmod +x play.sh

  - "echo #!/bin/sh >> spec.sh"
  - >
    echo "sudo -E su -l $USER -c 'rvm use default; cd $TRAVIS_BUILD_DIR && rake spec'" >> spec.sh
  - chmod +x spec.sh

  - rake init:links
script:
  # Syntax check
  - ansible-playbook -i inventory travis-playbook.yml --syntax-check

  # Play test
  - travis_wait 40 ./play.sh

  # Idempotence test
  - ./play.sh > idempotence.out

  - >
    grep -q "changed=0.*failed=0" idempotence.out
    && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && cat idempotence.out && exit 1)

  # Serverspec
  # - travis_wait 50 ./spec.sh
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
