---
sudo: required
dist: trusty

language: generic

env:
  - ANSIBLE_VERSION="1.9" PHP_VERSION="5.6.19"
  - ANSIBLE_VERSION="2.0" PHP_VERSION="5.6.19"
  - ANSIBLE_VERSION="1.9" PHP_VERSION="7.0.3"
  - ANSIBLE_VERSION="2.0" PHP_VERSION="7.0.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - sudo pip install "ansible~=$ANSIBLE_VERSION"
  - sudo ansible-galaxy install bbatsche.Nginx
script:
  - echo localhost > inventory

  # Syntax check
  - ansible-playbook -i inventory travis-playbook.yml --syntax-check

  # Play test
  - travis_wait ansible-playbook -i inventory travis-playbook.yml --connection=local -ephp_version="$PHP_VERSION"

  # Idempotence test
  - >
    ansible-playbook -i inventory travis-playbook.yml --connection=local -ephp_version="$PHP_VERSION"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
