---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    php_version: "7.1.10"

  roles:
    - role: bbatsche.Nginx
      site_type: php

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
