---
- name: Check for Composer
  stat: path={{ phpenv_root }}/versions/{{ php_version }}/composer/composer.phar
  register: composer_result

- name: Download Composer Installer
  get_url: url=https://getcomposer.org/installer dest=/tmp/install-composer.php
  when: composer_result.stat.exists == false

- name: Create Composer Directory
  file: name={{ phpenv_root }}/versions/{{ php_version }}/composer state=directory

- name: Install Composer
  phpenv:
    shell: php /tmp/install-composer.php --install-dir={{ phpenv_root }}/versions/{{ php_version }}/composer
    creates: "{{ phpenv_root }}/versions/{{ php_version }}/composer/composer.phar"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  notify: Rehash Phpenv

- name: Install PHPUnit
  phpenv:
    shell: composer global require phpunit/phpunit:{{ phpunit_version }} --prefer-dist --no-interaction
    creates: "{{ phpenv_root }}/versions/{{ php_version }}/composer/vendor/bin/phpunit"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  register: phpunit_result
  changed_when: phpunit_result | changed and 'Nothing to install or update' not in phpunit_result.stderr
  when: env_name == "dev"
  notify: Rehash Phpenv

- name: Install PsySH
  phpenv:
    shell: composer global require psy/psysh:{{ psysh_version }} --prefer-dist --no-interaction
    creates: "{{ phpenv_root }}/versions/{{ php_version }}/composer/vendor/bin/psysh"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  register: psysh_result
  changed_when: psysh_result | changed and 'Nothing to install or update' not in psysh_result.stderr
  when: env_name == "dev"
  notify: Rehash Phpenv
