---
- name: Install
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php5
    - php5-dev
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mcrypt
    - php5-mysqlnd
    - php5-pgsql
    - php5-pspell
    - php5-redis
    - php5-readline
    - php5-sqlite
    - php-pear
    - libyaml-dev
  notify: Restart FPM

- name: Install Xdebug
  apt: package=php5-xdebug state=present
  when: env_name == "dev"
  become: yes
  notify: Restart FPM

- name: Disable Xdebug in CLI
  file: path=/etc/php5/cli/conf.d/20-xdebug.ini state=absent
  become: yes

- name: Find Extension Directory
  command: php-config --extension-dir
  changed_when: no
  register: ext_dir

- name: Install PECL Extensions
  shell: yes '' | pecl install {{ item.name }}-{{ item.version }}
  args:
    creates: "{{ ext_dir.stdout }}/{{ item.name }}.so"
  with_items: "{{ pecl_extensions | default([]) }}"
  become: yes
  notify: Restart FPM

- name: Create Extension Config
  template: src=extension.ini.j2 dest=/etc/php5/mods-available/{{ item.name }}.ini
  with_items: "{{ pecl_extensions | default([]) }}"
  become: yes
  notify: Restart FPM

- name: Enable PECL Extensions
  command: php5enmod {{ item.name }} creates=/etc/php5/fpm/conf.d/{{ item.weight | default(20) }}-{{ item.name }}.ini
  with_items: "{{ pecl_extensions | default([]) }}"
  become: yes
  notify: Restart FPM

- name: Enable mcrypt Extension
  command: php5enmod mcrypt creates=/etc/php5/fpm/conf.d/20-mcrypt.ini
  become: yes
  notify: Restart FPM

- name: Delete Default FPM Pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  become: yes
  notify: Restart FPM

- name: Delete old FPM Log
  file: path=/var/log/php5-fpm.log state=absent
  become: yes

- name: Create FPM Run Directory
  file: path=/var/run/php-fpm state=directory
  become: yes

- name: Copy php.ini
  template: src=php.ini.j2 dest={{ item }}
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/fpm/php.ini
  become: yes
  notify: Restart FPM

- name: Copy FPM Config
  template: src=fpm.conf.j2 dest=/etc/php5/fpm/php-fpm.conf
  become: yes
  notify: Restart FPM

- name: Copy FPM Pool Config
  template: src=fpm-pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ domain }}.conf
  become: yes
  when: domain is defined
  notify: Restart FPM

- name: Set Path Variables
  set_fact:
    log_dir: /var/log/php
    session_path: /var/lib/php5/session
    log_files:
      - /var/log/php/fpm-error.log
    composer_path: /usr/local/bin/composer
    composer_dir: "{{ ansible_user_dir }}/.composer"

- name: Add Domain Slow Log Path
  set_fact:
    log_files: "{{ log_files }} + [ '/var/log/php/{{ domain }}-slow.log' ]"
  when: domain is defined

- include: suhosin.yml
  when: enable_suhosin
