---
- name: Install Build Dependencies
  apt: name={{ item }} state=present
  with_items:
    - aspell
    - aspell-en
    - autoconf
    - automake
    - bison
    - build-essential
    - libtool
    - libaspell-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libfreetype6-dev
    - libgmp-dev
    - libicu-dev
    - libjpeg-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - libmcrypt-dev
    - libmysqlclient-dev
    - libpq-dev
    - libpng12-dev
    - libpspell-dev
    - libreadline-dev
    - librecode-dev
    - libssl-dev
    - libxml2-dev
    - libxpm-dev
    - libxslt1-dev
    - libyaml-dev
    - re2c
  become: yes

- name: Link gmp.h to a Usable Location
  file:
    src: /usr/include/x86_64-linux-gnu/gmp.h
    dest: /usr/include/gmp.h
    state: link
  become: yes

- name: Copy Phpenv Definition
  template: src=phpenv_definition.j2 dest=/tmp/{{ php_version }}

- name: Install PHP
  phpenv:
    arguments: /tmp/{{ php_version }}
    php_version: "{{ php_version }}"
    phpenv_root: "{{ phpenv_root }}"
  notify: Rehash Phpenv

- name: Copy FPM Init Script
  template: src=fpm-init.sh.j2 dest=/etc/init.d/php{{ php_version }}-fpm mode=0755
  become: yes
  notify: Update FPM RC

- name: Copy FPM Upstart Config
  template: src=fpm-upstart.conf.j2 dest=/etc/init/php{{ php_version }}-fpm.conf
  become: yes
  when: ansible_distribution_release == "trusty"

- name: Copy FPM Systemd Config
  template: src=fpm-systemd.conf.j2 dest=/lib/systemd/system/php{{ php_version }}-fpm.service
  become: yes
  when: ansible_distribution_release == "xenial"
  notify: Enable FPM Systemd Service

- name: Delete Default FPM Config
  file: name={{ phpenv_root }}/versions/{{ php_version }}/etc/php-fpm.conf.default state=absent
  notify: Restart FPM

- name: Copy php.ini
  template: src=php.ini.j2 dest={{ phpenv_root }}/versions/{{ php_version }}/etc/php.ini
  notify: Restart FPM

- name: Copy FPM Config
  template: src=fpm.conf.j2 dest={{ phpenv_root }}/versions/{{ php_version }}/etc/php-fpm.conf
  notify: Restart FPM

- name: Create Pool Directory
  file: name={{ phpenv_root }}/versions/{{ php_version }}/etc/pool.d state=directory

- name: Copy FPM Pool Config
  template: src=fpm-pool.conf.j2 dest={{ phpenv_root }}/versions/{{ php_version }}/etc/pool.d/{{ domain }}.conf
  when: domain is defined
  notify: Restart FPM
