---
# Note: Do not put use template or file tasks when in a tasks sub directory!
# Ansible 1.9 will not determine the path correctly.

- name: Install Composer
  command: >
    php /tmp/install-composer.php --install-dir=/usr/local/bin --filename=composer
    creates={{ composer_path }}
  become: yes

- name: Install Composer Packages
  command: "composer global require {{ item.name }}:{{ item.version }} --prefer-dist --no-interaction"
  args:
    creates: "{{ composer_dir }}/vendor/{{ item.name }}"
  register: composer_result
  changed_when: composer_result | changed and 'Nothing to install or update' not in composer_result.stderr
  with_items: "{{ composer_packages | default([]) }}"
