---
- hosts: all
  vars_files:
  - "../../defaults/main.yml"
  - "../../vars/main.yml"
  vars:
    site_type: php
    domain: phpenv-test.dev
    php_version: 7.0.3
    xdebug_version: 2.4.0
    phpunit_version: "~5.2"
    pecl_extensions:
    - name: yaml
      version: 2.0.0RC7
    - name: imagick
      version: 3.4.0
  roles:
  - bbatsche.Nginx
  tasks:
  - include: "../../tasks/main.yml"
  handlers:
  - include: "../../handlers/main.yml"
  - name: Restart FPM
    service: name=php{{ php_version }}-fpm state=restarted
    become: true
  - name: Rehash Phpenv
    phpenv:
      command: rehash
      php_version: "{{ php_version }}"
      phpenv_root: "{{ phpenv_root }}"
  - name: Update RC
    command: update-rc.d php{{ php_version }}-fpm defaults
    become: true
