---
- hosts: all

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  roles:
    - role: bbatsche.Nginx
      site_type: php

  post_tasks:
    - name: Truncate Error Log
      command: truncate -s0 {{ log_dir }}/error.log
      become: yes

    - block:
      - name: Create Disabled Function Test
        copy:
          content: "<?php shell_exec('pwd');"
          dest: "{{ http_root }}/{{ domain }}/public/disabled_functions_test.php"

      - name: Create Openbase Dir Test
        copy:
          content: "<?php readfile(!empty($_GET['path']) ? $_GET['path'] : '/etc/passwd');"
          dest: "{{ http_root }}/{{ domain }}/public/open_basedir_test.php"

      - name: Create Session Test
        copy:
          content: "<?php session_start(); echo session_status();"
          dest: "{{ http_root }}/{{ domain }}/public/session_test.php"

      - name: Create Log Test
        copy:
          content: "<?php error_log('Test error message');"
          dest: "{{ http_root }}/{{ domain }}/public/error_test.php"
      when: domain is defined

  tasks:
    - include: ../../tasks/main.yml

  handlers:
    - include: ../../handlers/main.yml
