---
- name: Check for Composer
  stat: path={{ phpenv_root }}/versions/{{ php_version }}/composer/composer.phar
  register: composer_result

- name: Download Composer Installer
  get_url: url=https://getcomposer.org/installer dest=/tmp/install-composer.php
  when: composer_result.stat.exists == false

- name: Create Composer Directory
  file: name={{ phpenv_root }}/versions/{{ php_version }}/composer state=directory

- name: Install Composer
  phpenv:
    shell: php /tmp/install-composer.php --install-dir={{ phpenv_root }}/versions/{{ php_version }}/composer
    creates: "{{ phpenv_root }}/versions/{{ php_version }}/composer/composer.phar"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  notify: Rehash Phpenv

- name: Install Composer Packages
  phpenv:
    shell: "composer global require {{ item.name }}:{{ item.version }} --prefer-dist --no-interaction"
    creates: "{{ phpenv_root }}/versions/{{ php_version }}/composer/vendor/{{ item.name }}"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  register: composer_result
  changed_when: composer_result | changed and 'Nothing to install or update' not in composer_result.stderr
  notify: Rehash Phpenv
  with_items: "{{ composer_packages | default([]) }}"
