---
# Note: Do not put use template or file tasks when in a tasks sub directory!
# Ansible 1.9 will not determine the path correctly.

- name: Install Composer
  phpenv:
    shell: php /tmp/install-composer.php --install-dir={{ composer_dir }}
    creates: "{{ composer_path }}"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  notify: Rehash Phpenv

- name: Install Composer Packages
  phpenv:
    shell: "composer global require {{ item.name }}:{{ item.version }} --prefer-dist --no-interaction"
    creates: "{{ composer_dir }}/vendor/{{ item.name }}"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  register: composer_result
  changed_when: composer_result | changed and 'Nothing to install or update' not in composer_result.stderr
  notify: Rehash Phpenv
  with_items: "{{ composer_packages | default([]) }}"
