---
- name: Copy Upstart Config
  template: src=fpm-upstart.conf.j2 dest=/etc/init/php{{ php_version }}-fpm.conf
  become: yes
  notify: Update RC

- name: Copy Init Script
  template: src=fpm-init.sh.j2 dest=/etc/init.d/php{{ php_version }}-fpm mode=0755
  become: yes
  notify: Update RC

- name: Delete Default FPM Config
  file: name={{ phpenv_root }}/versions/{{ php_version }}/etc/php-fpm.conf.default state=absent
  notify: Restart FPM

- name: Copy FPM Config
  template: src=fpm.conf.j2 dest={{ phpenv_root }}/versions/{{ php_version }}/etc/php-fpm.conf
  notify: Restart FPM

- name: Create Pool Directory
  file: name={{ phpenv_root }}/versions/{{ php_version }}/etc/pool.d state=directory

- name: Check for FPM Error Log
  stat: path={{ phpenv_root }}/versions/{{ php_version }}/var/log/fpm-error.log
  register: fpm_error_log

- name: Check for Domain Slow Log
  stat: path={{ phpenv_root }}/versions/{{ php_version }}/var/log/{{ domain }}.slow.log
  when: domain | default("") != ""
  register: fpm_slow_log

- name: Create FPM Error Log Permissions
  file:
    name: "{{ phpenv_root }}/versions/{{ php_version }}/var/log/fpm-error.log"
    state: touch
    mode: 0664
    owner: "{{ ansible_ssh_user }}"
    group: www-data
  become: yes
  when: fpm_error_log.stat.exists == false

- name: Create Domain Slow Log Permissions
  file:
    name: "{{ phpenv_root }}/versions/{{ php_version }}/var/log/{{ domain }}.slow.log"
    state: touch
    mode: 0664
    owner: "{{ ansible_ssh_user }}"
    group: www-data
  become: yes
  when: domain | default("") != "" and fpm_slow_log.stat.exists == false

- name: Copy FPM Pool Config
  template: src=fpm-pool.conf.j2 dest={{ phpenv_root }}/versions/{{ php_version }}/etc/pool.d/{{ domain }}.conf
  when: domain | default("") != ""
  notify: Restart FPM
