---
- name: Install Build Dependencies
  apt: name={{ item }} state=present
  with_items:
    - aspell
    - aspell-en
    - autoconf
    - automake
    - bison
    - build-essential
    - libtool
    - libaspell-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libfreetype6-dev
    - libgmp-dev
    - libicu-dev
    - libjpeg-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - libmcrypt-dev
    - libmysqlclient-dev
    - libpq-dev
    - libpng12-dev
    - libpspell-dev
    - libreadline-dev
    - librecode-dev
    - libssl-dev
    - libxml2-dev
    - libxpm-dev
    - libxslt1-dev
    - libyaml-dev
    - re2c
  become: yes

- name: Link gmp.h to a Usable Location
  file:
    src: /usr/include/x86_64-linux-gnu/gmp.h
    dest: /usr/include/gmp.h
    state: link
  become: yes

- name: Copy Phpenv Definition
  template: src=phpenv_definition.j2 dest=/tmp/{{ php_version }}

- name: Install
  phpenv:
    arguments: /tmp/{{ php_version }}
    php_version: "{{ php_version }}"
    phpenv_root: "{{ phpenv_root }}"
  notify: Rehash Phpenv

- name: Set Path Variables
  set_fact:
    log_path:
      - "{{ phpenv_root }}/versions/{{ php_version }}/var/log"
    session_path: "{{ phpenv_root }}/versions/{{ php_version }}/var/run/session"
    config_path:
      - "{{ phpenv_root}}/versions/{{ php_version }}/etc/php.ini"
    fpm_pool_path: "{{ phpenv_root }}/versions/{{ php_version }}/etc/pool.d"

- include: extensions.yml
- include: fpm.yml
- include: composer.yml
